# Generated by Django 3.1.6 on 2021-03-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dete_of_birth',
            new_name='date_of_birth',
        ),
    ]
